# Generated by Django 4.2 on 2023-04-18 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_sessao_sobrevivente_sal_sobrevivente_senha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sobrevivente')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.itemcomercial')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.oferta')),
            ],
        ),
    ]
