# Generated by Django 4.2 on 2023-04-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_relato_relator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='usuario',
            new_name='vendedor',
        ),
    ]
